#
# ============================================================================
#  OpenSIPS 3.6 -- Session Border Controller for Microsoft Teams
#                  Direct Routing / Direct SIP trunking (inbound + outbound)
# ----------------------------------------------------------------------------
#  *** DO NOT EDIT THIS FILE FOR SITE VALUES ***
#  All site-specific values come from local.m4 (M_* macros). Regenerate with:
#       make            (== m4 -P local.m4 opensips.m4 > opensips.cfg)
#
#  Topology:
#       Microsoft Teams  <==TLS 5560, SRTP==>  [ OpenSIPS + rtpengine ]  <==RTP==>  carrier/core
#
#  Highlights:
#    * TLS (mutual) is served ONLY on port 5560 (Teams leg). No other TLS port.
#    * Full multi-tenancy on <tenant>.teams.ucp.voiceland.dev / .global
#    * rtpengine bridges Teams SRTP (RTP/SAVP) <-> carrier RTP (RTP/AVP)
#    * Per-tenant FQDN is placed in the Teams-facing Contact and Record-Route,
#      which is how Microsoft attributes the call to the correct trunk.
# ============================================================================

####### Global Parameters #########

log_level=M_LOG_LEVEL
xlog_level=M_LOG_LEVEL
log_stderror=no
log_facility=LOG_LOCAL0

udp_workers=M_UDP_WORKERS
tcp_workers=M_TCP_WORKERS

disable_tcp=no
auto_aliases=no

mpath="M_MODULES_PATH"

####### Modules (load order matters: db_mysql + tls_mgm before proto_tls) #########

loadmodule "M_DB_MODULE"
loadmodule "proto_udp.so"
loadmodule "proto_tcp.so"
loadmodule "tls_mgm.so"
loadmodule "proto_tls.so"
loadmodule "sl.so"
loadmodule "tm.so"
loadmodule "signaling.so"
loadmodule "rr.so"
loadmodule "maxfwd.so"
loadmodule "sipmsgops.so"
loadmodule "uac.so"
loadmodule "domain.so"
loadmodule "dialog.so"
loadmodule "rtpengine.so"
loadmodule "htable.so"
loadmodule "mi_fifo.so"

####### Module Parameters #########

# ---- management interface ----
modparam("mi_fifo", "fifo_name", "M_FIFO_PATH")

# ---- transaction module ----
modparam("tm", "fr_timeout", 5)
modparam("tm", "fr_inv_timeout", 120)
modparam("tm", "restart_fr_on_each_reply", 0)
# make AVPs set in the request route visible inside onreply_route
modparam("tm", "onreply_avp_mode", 1)

# ---- record routing (SBC stays in the signalling path on both legs) ----
modparam("rr", "append_fromtag", 1)
modparam("rr", "enable_double_rr", 1)

# ---- dialog tracking (call state, in-dialog routing, stats) ----
modparam("dialog", "dlg_match_mode", 1)
modparam("dialog", "default_timeout", 43200)

# ---- From/PAI rewrite restoration on the carrier leg ----
modparam("uac", "restore_mode", "auto")

# ---- rtpengine media relay ----
modparam("rtpengine", "rtpengine_sock", "M_RTPENGINE_SOCK")
modparam("rtpengine", "rtpengine_disable_tout", 20)

# ---- in-memory map: carrier source IP -> tenant FQDN (outbound branding) ----
modparam("htable", "htable", "carrier_src=>size=M_HTABLE_SIZE;")

# ---- TLS: ALL certificates/domains are managed in the database (tls_mgm) ----
# Server + client TLS domains live in the `tls_mgm` table. Certificates, keys
# and CA chains are stored as BLOBs and rotated by tls-rotation/manage-tls.py,
# which hot-reloads them with:  opensips-cli -x mi tls_mgm:reload
modparam("tls_mgm", "tls_library", "openssl")
modparam("tls_mgm", "db_url",   "M_DB_URL")
modparam("tls_mgm", "db_table", "M_TLS_DB_TABLE")

# ---- domain: the authoritative list of allowed tenant domains ----
# Each tenant FQDN is a row in the `domain` table; its `attrs` column holds the
# carrier trunk SIP URI used for inbound (Teams -> carrier) routing.
# db_mode=1 caches the table; reload with:  opensips-cli -x mi domain:reload
modparam("domain", "db_url",       "M_DB_URL")
modparam("domain", "db_mode",      M_DOMAIN_DB_MODE)
modparam("domain", "domain_table", "M_DOMAIN_TABLE")

####### Listening sockets #########
# TLS is exposed ONLY on 5560 (Teams). Carrier leg is plain UDP/TCP on 5060.
socket=tls:M_TEAMS_TLS_LISTEN_IP:M_TEAMS_TLS_PORT as M_TEAMS_TLS_ADVERTISED_IP:M_TEAMS_TLS_PORT
socket=udp:M_CARRIER_LISTEN_IP:M_CARRIER_SIP_PORT as M_CARRIER_ADVERTISED_IP:M_CARRIER_SIP_PORT
socket=tcp:M_CARRIER_LISTEN_IP:M_CARRIER_SIP_PORT as M_CARRIER_ADVERTISED_IP:M_CARRIER_SIP_PORT

####### Startup: provision carrier source IPs #########
# Tenant domains + inbound trunks live in the DB `domain` table.
# Only the reverse map (carrier source IP -> tenant FQDN), used to brand
# outbound calls towards Teams, is kept in this in-memory table.
startup_route {
	xlog("L_INFO", "[teams-sbc] provisioning carrier sources (env=M_DEPLOY_ENV, base=M_TEAMS_TENANT_BASE_DOMAIN)\n");
	M_CARRIER_SRC_PROVISIONING
}

####### Main request routing #########
route {

	# --- basic sanity ---
	if (!mf_process_maxfwd_header("10")) {
		send_reply(483, "Too Many Hops");
		exit;
	}

	# --- OPTIONS keep-alive from Teams (out-of-dialog): answer locally ---
	if (is_method("OPTIONS") && !has_totag()) {
		route(TEAMS_OPTIONS_KEEPALIVE);
		exit;
	}

	# --- sequential (in-dialog) requests ---
	if (has_totag()) {
		if (loose_route()) {
			if (is_method("BYE")) {
				rtpengine_delete();
			} else if (is_method("INVITE")) {
				# re-INVITE / session refresh
				route(INDIALOG_INVITE);
			}
			route(RELAY);
		} else {
			if (is_method("ACK")) {
				# ACK for a locally generated negative reply, or for a 2xx
				# whose transaction is still around
				if (t_check_trans())
					t_relay();
				exit;
			}
			send_reply(404, "Not Here");
		}
		exit;
	}

	# --- initial requests ---
	if (is_method("CANCEL")) {
		if (t_check_trans())
			t_relay();
		exit;
	}

	if (!is_method("INVITE")) {
		send_reply(405, "Method Not Allowed");
		exit;
	}

	# --- determine direction and bridge ---
	if (route(IS_FROM_TEAMS)) {
		route(FROM_TEAMS_TO_CARRIER);
	} else if (route(IS_FROM_CARRIER)) {
		route(FROM_CARRIER_TO_TEAMS);
	} else {
		xlog("L_WARN", "[teams-sbc] rejecting INVITE from untrusted source $si:$sp ($proto)\n");
		send_reply(403, "Forbidden");
	}
	exit;
}

# ---------------------------------------------------------------------------
#  Direction detection
# ---------------------------------------------------------------------------
route[IS_FROM_TEAMS] {
	# Arrived over TLS (only on 5560) AND from a Microsoft signalling subnet.
	if ($proto == "tls" && $si =~ "M_TEAMS_SRC_IP_REGEX")
		return(1);
	return(-1);
}

route[IS_FROM_CARRIER] {
	# Source IP is a provisioned carrier trunk.
	if ($sht(carrier_src=>$si) != NULL)
		return(1);
	return(-1);
}

# ---------------------------------------------------------------------------
#  OPTIONS keep-alive answered to Teams. Microsoft marks the trunk healthy when
#  it receives a 200 OK whose Contact host is an FQDN (never a bare IP).
# ---------------------------------------------------------------------------
route[TEAMS_OPTIONS_KEEPALIVE] {
	append_to_reply("Contact: <sip:$rd:M_TEAMS_TLS_PORT;transport=tls>\r\n");
	append_to_reply("Allow: INVITE, ACK, CANCEL, BYE, OPTIONS, INFO\r\n");
	append_to_reply("Accept: application/sdp\r\n");
	send_reply(200, "OK");
}

# ---------------------------------------------------------------------------
#  INBOUND  :  Teams  -->  SBC  -->  carrier
# ---------------------------------------------------------------------------
route[FROM_TEAMS_TO_CARRIER] {
	# Tenant identity = host of the Request-URI (the tenant FQDN Microsoft sends
	# to). Validate it against the DB `domain` table and pull the carrier trunk
	# SIP URI from that domain's `attrs` column in one lookup.
	if (!is_uri_host_local($var(trunk))) {
		xlog("L_WARN", "[teams-sbc] inbound INVITE for non-local tenant domain $rd\n");
		send_reply(404, "Unknown Tenant Domain");
		exit;
	}
	if ($var(trunk) == NULL || $var(trunk) == "") {
		xlog("L_WARN", "[teams-sbc] no trunk (domain.attrs) provisioned for tenant $rd\n");
		send_reply(404, "Tenant Not Provisioned");
		exit;
	}
	$avp(tenant_fqdn) = $rd;
	$avp(direction) = "in";

	xlog("L_INFO", "[teams-sbc] IN  $ci tenant=$rd $fU -> $rU via $var(trunk)\n");

	# Topology hiding: present the SBC carrier address as Contact.
	remove_hf("Contact");
	append_hf("Contact: <sip:M_SBC_CONTACT_USER@M_CARRIER_ADVERTISED_IP:M_CARRIER_SIP_PORT>\r\n");

	# Double Record-Route: outbound(carrier)=SBC IP, inbound(Teams)=tenant FQDN.
	record_route_preset("M_CARRIER_ADVERTISED_IP:M_CARRIER_SIP_PORT",
	                    "$avp(tenant_fqdn):M_TEAMS_TLS_PORT;transport=tls");

	# Media: Teams SRTP --> carrier RTP.
	if (has_body_part("application/sdp"))
		rtpengine_offer("M_RTPENGINE_FLAGS_TO_CARRIER");

	$du = $var(trunk);
	$fs = "M_CARRIER_FORCE_SOCKET";

	create_dialog();
	$dlg_val(tenant_fqdn) = $avp(tenant_fqdn);
	$dlg_val(direction)   = "in";

	t_on_reply("MANAGE_REPLY");
	t_on_failure("MANAGE_FAILURE");
	route(RELAY);
}

# ---------------------------------------------------------------------------
#  OUTBOUND :  carrier  -->  SBC  -->  Teams
# ---------------------------------------------------------------------------
route[FROM_CARRIER_TO_TEAMS] {
	$avp(tenant_fqdn) = $sht(carrier_src=>$si);
	$avp(direction)   = "out";

	# The branded tenant FQDN must be an allowed domain (DB `domain` table).
	if (!is_domain_local("$avp(tenant_fqdn)")) {
		xlog("L_WARN", "[teams-sbc] carrier $si mapped to non-local tenant $avp(tenant_fqdn)\n");
		send_reply(403, "Forbidden");
		exit;
	}

	xlog("L_INFO", "[teams-sbc] OUT $ci tenant=$avp(tenant_fqdn) $fU -> $rU to Teams\n");

	# Microsoft requires E.164 (+CC...) in the Request-URI / From / PAI.
	route(NORMALIZE_E164);

	# Calling identity must reference the tenant FQDN.
	uac_replace_from("$fn", "sip:$fU@$avp(tenant_fqdn)");
	if (!is_present_hf("P-Asserted-Identity"))
		append_hf("P-Asserted-Identity: <sip:$fU@$avp(tenant_fqdn)>\r\n");

	# SBC Contact MUST be the tenant FQDN: this is how Teams maps the call to
	# the correct tenant trunk. Wildcard cert + DNS make every tenant FQDN valid.
	remove_hf("Contact");
	append_hf("Contact: <sip:M_SBC_CONTACT_USER@$avp(tenant_fqdn):M_TEAMS_TLS_PORT;transport=tls>\r\n");

	# Double Record-Route: outbound(Teams)=tenant FQDN, inbound(carrier)=SBC IP.
	record_route_preset("$avp(tenant_fqdn):M_TEAMS_TLS_PORT;transport=tls",
	                    "M_CARRIER_ADVERTISED_IP:M_CARRIER_SIP_PORT");

	# Media: carrier RTP --> Teams SRTP.
	if (has_body_part("application/sdp"))
		rtpengine_offer("M_RTPENGINE_FLAGS_TO_TEAMS");

	# Send to the primary Microsoft proxy; MANAGE_FAILURE rolls to sip2/sip3.
	$avp(tp_idx) = 1;
	$du = "M_TEAMS_PROXY_1";
	$fs = "M_TEAMS_FORCE_SOCKET";

	create_dialog();
	$dlg_val(tenant_fqdn) = $avp(tenant_fqdn);
	$dlg_val(direction)   = "out";

	t_on_reply("MANAGE_REPLY");
	t_on_failure("MANAGE_FAILURE");
	route(RELAY);
}

# ---------------------------------------------------------------------------
#  In-dialog re-INVITE (hold/resume, session timer, codec change)
# ---------------------------------------------------------------------------
route[INDIALOG_INVITE] {
	if (route(IS_FROM_TEAMS))
		$avp(direction) = "in";
	else
		$avp(direction) = "out";

	$avp(tenant_fqdn) = $dlg_val(tenant_fqdn);

	if ($avp(direction) == "out") {
		remove_hf("Contact");
		append_hf("Contact: <sip:M_SBC_CONTACT_USER@$avp(tenant_fqdn):M_TEAMS_TLS_PORT;transport=tls>\r\n");
		if (has_body_part("application/sdp"))
			rtpengine_offer("M_RTPENGINE_FLAGS_TO_TEAMS");
	} else {
		remove_hf("Contact");
		append_hf("Contact: <sip:M_SBC_CONTACT_USER@M_CARRIER_ADVERTISED_IP:M_CARRIER_SIP_PORT>\r\n");
		if (has_body_part("application/sdp"))
			rtpengine_offer("M_RTPENGINE_FLAGS_TO_CARRIER");
	}

	t_on_reply("MANAGE_REPLY");
}

# ---------------------------------------------------------------------------
#  Reply processing (provisional + 2xx): finish media negotiation and rewrite
#  the Contact on the leg the reply is travelling towards.
# ---------------------------------------------------------------------------
onreply_route[MANAGE_REPLY] {
	if ($rs < 180 || $rs > 299)
		return;

	if (has_body_part("application/sdp")) {
		if ($avp(direction) == "in")
			rtpengine_answer("M_RTPENGINE_FLAGS_TO_TEAMS");
		else
			rtpengine_answer("M_RTPENGINE_FLAGS_TO_CARRIER");
	}

	remove_hf("Contact");
	if ($avp(direction) == "in") {
		# reply heading to Teams -> tenant FQDN Contact
		append_hf("Contact: <sip:M_SBC_CONTACT_USER@$avp(tenant_fqdn):M_TEAMS_TLS_PORT;transport=tls>\r\n");
	} else {
		# reply heading to carrier -> SBC carrier Contact
		append_hf("Contact: <sip:M_SBC_CONTACT_USER@M_CARRIER_ADVERTISED_IP:M_CARRIER_SIP_PORT>\r\n");
	}
}

# ---------------------------------------------------------------------------
#  Failure handling: Microsoft proxy fail-over for outbound calls, plus media
#  tear-down once the call definitively fails.
# ---------------------------------------------------------------------------
failure_route[MANAGE_FAILURE] {
	if (t_was_cancelled())
		exit;

	# Outbound: roll over to the next Microsoft proxy on timeout / 5xx.
	if ($avp(direction) == "out" && t_check_status("(408|5[0-9][0-9])")) {
		if (route(NEXT_TEAMS_PROXY)) {
			t_on_reply("MANAGE_REPLY");
			t_on_failure("MANAGE_FAILURE");
			route(RELAY);
			exit;
		}
	}

	# Give up: release the media session.
	rtpengine_delete();
}

route[NEXT_TEAMS_PROXY] {
	$avp(tp_idx) = $avp(tp_idx) + 1;
	if ($avp(tp_idx) == 2) {
		xlog("L_NOTICE", "[teams-sbc] $ci failing over to Teams proxy #2\n");
		$du = "M_TEAMS_PROXY_2";
		$fs = "M_TEAMS_FORCE_SOCKET";
		return(1);
	}
	if ($avp(tp_idx) == 3) {
		xlog("L_NOTICE", "[teams-sbc] $ci failing over to Teams proxy #3\n");
		$du = "M_TEAMS_PROXY_3";
		$fs = "M_TEAMS_FORCE_SOCKET";
		return(1);
	}
	return(-1);
}

# ---------------------------------------------------------------------------
#  Normalise the Request-URI user to E.164 (+CC...) for Microsoft Teams.
# ---------------------------------------------------------------------------
route[NORMALIZE_E164] {
	if ($rU == NULL)
		return;
	if ($rU =~ "^\+[1-9][0-9]+$")
		return;
	if ($rU =~ "^00[1-9][0-9]+$") {
		strip(2);
		$rU = "+" + $rU;
		return;
	}
	if ($rU =~ "^[1-9][0-9]+$")
		$rU = "+" + $rU;
}

# ---------------------------------------------------------------------------
#  Stateful relay
# ---------------------------------------------------------------------------
route[RELAY] {
	if (!t_relay())
		send_reply(500, "Internal Server Error");
	exit;
}
