#
# ============================================================================
#  OpenSIPS 3.6 -- Session Border Controller for Microsoft Teams
#                  Direct Routing / Direct SIP trunking (inbound + outbound)
# ----------------------------------------------------------------------------
#  *** DO NOT EDIT THIS FILE FOR SITE VALUES ***
#  All site-specific values come from local.m4 (M_* macros). Regenerate with:
#       make            (== m4 -P local.m4 opensips.m4 > opensips.cfg)
#
#  Topology:
#    Microsoft Teams  <==TLS 5560, SRTP==>  [ OpenSIPS + rtpengine ]  <==TCP 5560, RTP==>  core
#                                                                       eu.ucp.voiceland.{dev,global}
#
#  Routing:
#    * Teams  -> core : every call is relayed to the core FQDN:5560/TCP.
#    * core   -> Teams: tenant = From-URI host (or P-Asserted-Identity host);
#                       the tenant must exist in the `tls_mgm` table; then the
#                       call is sent to the Microsoft pstnhub proxies.
#    * Trusted core source IPs live in the `address` table and are refreshed
#      from DNS every 5 minutes by the rotation sidecar.
#    * All TLS certificates + tenant identities are managed in the database.
# ============================================================================

####### Global Parameters #########

log_level=M_LOG_LEVEL
xlog_level=M_LOG_LEVEL
log_stderror=no
log_facility=LOG_LOCAL0

udp_workers=M_UDP_WORKERS
tcp_workers=M_TCP_WORKERS

disable_tcp=no
auto_aliases=no

mpath="M_MODULES_PATH"

####### Modules #########

loadmodule "M_DB_MODULE"
loadmodule "proto_udp.so"
loadmodule "proto_tcp.so"
loadmodule "tls_mgm.so"
loadmodule "proto_tls.so"
loadmodule "sl.so"
loadmodule "tm.so"
loadmodule "signaling.so"
loadmodule "rr.so"
loadmodule "maxfwd.so"
loadmodule "sipmsgops.so"
loadmodule "uac.so"
loadmodule "permissions.so"
loadmodule "sqlops.so"
loadmodule "dialog.so"
loadmodule "rtpengine.so"
loadmodule "mi_fifo.so"
loadmodule "httpd.so"
loadmodule "mi_http.so"

####### Module Parameters #########

# ---- management interfaces ----
modparam("mi_fifo", "fifo_name", "M_FIFO_PATH")
modparam("httpd", "ip", "M_MI_HTTP_IP")
modparam("httpd", "port", M_MI_HTTP_PORT)

# ---- transaction module ----
modparam("tm", "fr_timeout", 5)
modparam("tm", "fr_inv_timeout", 120)
modparam("tm", "restart_fr_on_each_reply", 0)
modparam("tm", "onreply_avp_mode", 1)

# ---- record routing (SBC stays in the signalling path on both legs) ----
modparam("rr", "append_fromtag", 1)
modparam("rr", "enable_double_rr", 1)

# ---- dialog tracking ----
modparam("dialog", "dlg_match_mode", 1)
modparam("dialog", "default_timeout", 43200)

# ---- From/PAI rewrite restoration on the core leg ----
modparam("uac", "restore_mode", "auto")

# ---- rtpengine media relay ----
modparam("rtpengine", "rtpengine_sock", "M_RTPENGINE_SOCK")
modparam("rtpengine", "rtpengine_disable_tout", 20)

# ---- permissions: trusted core source IPs (refreshed from DNS every 5 min) ----
modparam("permissions", "db_url", "M_DB_URL")
modparam("permissions", "address_table", "M_ADDRESS_TABLE")

# ---- sqlops: runtime tenant lookups against the tls_mgm table ----
modparam("sqlops", "db_url", "M_DB_URL")

# ---- TLS: ALL certificates/domains are managed in the database (tls_mgm) ----
# Rotated by tls-rotation/manage-tls.py, hot-reloaded via MI tls_mgm:reload.
modparam("tls_mgm", "tls_library", "openssl")
modparam("tls_mgm", "db_url",   "M_DB_URL")
modparam("tls_mgm", "db_table", "M_TLS_DB_TABLE")

####### Listening sockets #########
# TLS only on 5560 (Teams). Core leg is plain TCP (and UDP) towards eu.ucp.*.
socket=tls:M_TEAMS_TLS_LISTEN_IP:M_TEAMS_TLS_PORT as M_TEAMS_TLS_ADVERTISED_IP:M_TEAMS_TLS_PORT
socket=tcp:M_CORE_LISTEN_IP:M_CORE_SIP_PORT as M_CORE_ADVERTISED_IP:M_CORE_SIP_PORT
socket=udp:M_CORE_LISTEN_IP:M_CORE_SIP_PORT as M_CORE_ADVERTISED_IP:M_CORE_SIP_PORT

####### Main request routing #########
route {

	# --- basic sanity ---
	if (!mf_process_maxfwd_header("10")) {
		send_reply(483, "Too Many Hops");
		exit;
	}

	# --- OPTIONS keep-alive from Teams (out-of-dialog): answer locally ---
	if (is_method("OPTIONS") && !has_totag()) {
		route(TEAMS_OPTIONS_KEEPALIVE);
		exit;
	}

	# --- sequential (in-dialog) requests ---
	if (has_totag()) {
		if (loose_route()) {
			if (is_method("BYE")) {
				rtpengine_delete();
			} else if (is_method("INVITE")) {
				route(INDIALOG_INVITE);
			}
			route(RELAY);
		} else {
			if (is_method("ACK")) {
				if (t_check_trans())
					t_relay();
				exit;
			}
			send_reply(404, "Not Here");
		}
		exit;
	}

	# --- initial requests ---
	if (is_method("CANCEL")) {
		if (t_check_trans())
			t_relay();
		exit;
	}

	if (!is_method("INVITE")) {
		send_reply(405, "Method Not Allowed");
		exit;
	}

	# --- determine direction and bridge ---
	if (route(IS_FROM_TEAMS)) {
		route(FROM_TEAMS_TO_CORE);
	} else if (route(IS_FROM_CORE)) {
		route(FROM_CORE_TO_TEAMS);
	} else {
		xlog("L_WARN", "[teams-sbc] rejecting INVITE from untrusted source $si:$sp ($proto)\n");
		send_reply(403, "Forbidden");
	}
	exit;
}

# ---------------------------------------------------------------------------
#  Direction detection
# ---------------------------------------------------------------------------
route[IS_FROM_TEAMS] {
	# Arrived over TLS (only on 5560) AND from a Microsoft signalling subnet.
	if ($proto == "tls" && $si =~ "M_TEAMS_SRC_IP_REGEX")
		return(1);
	return(-1);
}

route[IS_FROM_CORE] {
	# Source IP is a trusted core node (address table group M_CORE_GROUP,
	# kept current by the 5-minute DNS refresh of M_CORE_IPS_FQDN).
	if (check_source_address(M_CORE_GROUP))
		return(1);
	return(-1);
}

# ---------------------------------------------------------------------------
#  OPTIONS keep-alive answered to Teams (FQDN Contact required by Microsoft).
# ---------------------------------------------------------------------------
route[TEAMS_OPTIONS_KEEPALIVE] {
	append_to_reply("Contact: <sip:$rd:M_TEAMS_TLS_PORT;transport=tls>\r\n");
	append_to_reply("Allow: INVITE, ACK, CANCEL, BYE, OPTIONS, INFO\r\n");
	append_to_reply("Accept: application/sdp\r\n");
	send_reply(200, "OK");
}

# ---------------------------------------------------------------------------
#  INBOUND  :  Teams  -->  SBC  -->  core (eu.ucp.voiceland.X:5560/TCP)
# ---------------------------------------------------------------------------
route[FROM_TEAMS_TO_CORE] {
	# Tenant FQDN that Microsoft addressed = host of the Request-URI; used only
	# to brand the Teams-facing Record-Route. Every call goes to the core.
	$avp(tenant_fqdn) = $rd;
	$avp(direction)   = "in";

	xlog("L_INFO", "[teams-sbc] IN  $ci tenant=$rd $fU -> $rU to core M_CORE_DST\n");

	# Topology hiding: present the SBC core address as Contact.
	remove_hf("Contact");
	append_hf("Contact: <sip:M_SBC_CONTACT_USER@M_CORE_ADVERTISED_IP:M_CORE_SIP_PORT;transport=M_CORE_TRANSPORT>\r\n");

	# Double Record-Route: outbound(core)=SBC core, inbound(Teams)=tenant FQDN.
	record_route_preset("M_CORE_ADVERTISED_IP:M_CORE_SIP_PORT;transport=M_CORE_TRANSPORT",
	                    "$avp(tenant_fqdn):M_TEAMS_TLS_PORT;transport=tls");

	# Media: Teams SRTP --> core RTP.
	if (has_body_part("application/sdp"))
		rtpengine_offer("M_RTPENGINE_FLAGS_TO_CORE");

	$du = "M_CORE_DST";
	$fs = "M_CORE_FORCE_SOCKET";

	create_dialog();
	$dlg_val(tenant_fqdn) = $avp(tenant_fqdn);
	$dlg_val(direction)   = "in";

	t_on_reply("MANAGE_REPLY");
	t_on_failure("MANAGE_FAILURE");
	route(RELAY);
}

# ---------------------------------------------------------------------------
#  OUTBOUND :  core  -->  SBC  -->  Teams
# ---------------------------------------------------------------------------
route[FROM_CORE_TO_TEAMS] {
	# Tenant identity comes from the From-URI host, else the P-Asserted-Identity
	# host; it must exist in the tls_mgm table.
	if (!route(RESOLVE_TENANT)) {
		xlog("L_WARN", "[teams-sbc] core $si: no tls_mgm tenant for From=$fd / PAI\n");
		send_reply(403, "Unknown Tenant");
		exit;
	}
	$avp(direction) = "out";

	xlog("L_INFO", "[teams-sbc] OUT $ci tenant=$avp(tenant_fqdn) $fU -> $rU to Teams\n");

	# Microsoft requires E.164 (+CC...) in the Request-URI / From / PAI.
	route(NORMALIZE_E164);

	# Calling identity must reference the tenant FQDN.
	uac_replace_from("$fn", "sip:$fU@$avp(tenant_fqdn)");
	if (!is_present_hf("P-Asserted-Identity"))
		append_hf("P-Asserted-Identity: <sip:$fU@$avp(tenant_fqdn)>\r\n");

	# SBC Contact MUST be the tenant FQDN: this is how Teams maps the call to
	# the correct tenant trunk.
	remove_hf("Contact");
	append_hf("Contact: <sip:M_SBC_CONTACT_USER@$avp(tenant_fqdn):M_TEAMS_TLS_PORT;transport=tls>\r\n");

	# Double Record-Route: outbound(Teams)=tenant FQDN, inbound(core)=SBC core.
	record_route_preset("$avp(tenant_fqdn):M_TEAMS_TLS_PORT;transport=tls",
	                    "M_CORE_ADVERTISED_IP:M_CORE_SIP_PORT;transport=M_CORE_TRANSPORT");

	# Media: core RTP --> Teams SRTP.
	if (has_body_part("application/sdp"))
		rtpengine_offer("M_RTPENGINE_FLAGS_TO_TEAMS");

	# Send to the primary Microsoft proxy; MANAGE_FAILURE rolls to sip2/sip3.
	$avp(tp_idx) = 1;
	$du = "M_TEAMS_PROXY_1";
	$fs = "M_TEAMS_FORCE_SOCKET";

	create_dialog();
	$dlg_val(tenant_fqdn) = $avp(tenant_fqdn);
	$dlg_val(direction)   = "out";

	t_on_reply("MANAGE_REPLY");
	t_on_failure("MANAGE_FAILURE");
	route(RELAY);
}

# ---------------------------------------------------------------------------
#  Resolve + validate the outbound tenant (From host, then PAI host) against
#  the tls_mgm table. Sets $avp(tenant_fqdn) and returns 1 on success.
# ---------------------------------------------------------------------------
route[RESOLVE_TENANT] {
	$var(cand) = $fd;
	if (route(TENANT_EXISTS)) {
		$avp(tenant_fqdn) = $var(cand);
		return(1);
	}
	if (is_present_hf("P-Asserted-Identity")) {
		$var(cand) = $(hdr(P-Asserted-Identity){nameaddr.uri}{uri.host});
		if (route(TENANT_EXISTS)) {
			$avp(tenant_fqdn) = $var(cand);
			return(1);
		}
	}
	return(-1);
}

route[TENANT_EXISTS] {
	if ($var(cand) == NULL || $var(cand) == "")
		return(-1);
	if (sql_query("SELECT domain FROM M_TLS_DB_TABLE WHERE domain='$(var(cand){s.escape.common})' OR match_sip_domain='$(var(cand){s.escape.common})' LIMIT 1",
	              "$avp(_tenant_chk)"))
		return(1);
	return(-1);
}

# ---------------------------------------------------------------------------
#  In-dialog re-INVITE (hold/resume, session timer, codec change)
# ---------------------------------------------------------------------------
route[INDIALOG_INVITE] {
	if (route(IS_FROM_TEAMS))
		$avp(direction) = "in";
	else
		$avp(direction) = "out";

	$avp(tenant_fqdn) = $dlg_val(tenant_fqdn);

	if ($avp(direction) == "out") {
		remove_hf("Contact");
		append_hf("Contact: <sip:M_SBC_CONTACT_USER@$avp(tenant_fqdn):M_TEAMS_TLS_PORT;transport=tls>\r\n");
		if (has_body_part("application/sdp"))
			rtpengine_offer("M_RTPENGINE_FLAGS_TO_TEAMS");
	} else {
		remove_hf("Contact");
		append_hf("Contact: <sip:M_SBC_CONTACT_USER@M_CORE_ADVERTISED_IP:M_CORE_SIP_PORT;transport=M_CORE_TRANSPORT>\r\n");
		if (has_body_part("application/sdp"))
			rtpengine_offer("M_RTPENGINE_FLAGS_TO_CORE");
	}

	t_on_reply("MANAGE_REPLY");
}

# ---------------------------------------------------------------------------
#  Reply processing (provisional + 2xx): finish media negotiation and rewrite
#  the Contact on the leg the reply is travelling towards.
# ---------------------------------------------------------------------------
onreply_route[MANAGE_REPLY] {
	if ($rs < 180 || $rs > 299)
		return;

	if (has_body_part("application/sdp")) {
		if ($avp(direction) == "in")
			rtpengine_answer("M_RTPENGINE_FLAGS_TO_TEAMS");
		else
			rtpengine_answer("M_RTPENGINE_FLAGS_TO_CORE");
	}

	remove_hf("Contact");
	if ($avp(direction) == "in") {
		# reply heading to Teams -> tenant FQDN Contact
		append_hf("Contact: <sip:M_SBC_CONTACT_USER@$avp(tenant_fqdn):M_TEAMS_TLS_PORT;transport=tls>\r\n");
	} else {
		# reply heading to core -> SBC core Contact
		append_hf("Contact: <sip:M_SBC_CONTACT_USER@M_CORE_ADVERTISED_IP:M_CORE_SIP_PORT;transport=M_CORE_TRANSPORT>\r\n");
	}
}

# ---------------------------------------------------------------------------
#  Failure handling: Microsoft proxy fail-over for outbound calls + media
#  tear-down once the call definitively fails.
# ---------------------------------------------------------------------------
failure_route[MANAGE_FAILURE] {
	if (t_was_cancelled())
		exit;

	if ($avp(direction) == "out" && t_check_status("(408|5[0-9][0-9])")) {
		if (route(NEXT_TEAMS_PROXY)) {
			t_on_reply("MANAGE_REPLY");
			t_on_failure("MANAGE_FAILURE");
			route(RELAY);
			exit;
		}
	}

	rtpengine_delete();
}

route[NEXT_TEAMS_PROXY] {
	$avp(tp_idx) = $avp(tp_idx) + 1;
	if ($avp(tp_idx) == 2) {
		xlog("L_NOTICE", "[teams-sbc] $ci failing over to Teams proxy #2\n");
		$du = "M_TEAMS_PROXY_2";
		$fs = "M_TEAMS_FORCE_SOCKET";
		return(1);
	}
	if ($avp(tp_idx) == 3) {
		xlog("L_NOTICE", "[teams-sbc] $ci failing over to Teams proxy #3\n");
		$du = "M_TEAMS_PROXY_3";
		$fs = "M_TEAMS_FORCE_SOCKET";
		return(1);
	}
	return(-1);
}

# ---------------------------------------------------------------------------
#  Normalise the Request-URI user to E.164 (+CC...) for Microsoft Teams.
# ---------------------------------------------------------------------------
route[NORMALIZE_E164] {
	if ($rU == NULL)
		return;
	if ($rU =~ "^\+[1-9][0-9]+$")
		return;
	if ($rU =~ "^00[1-9][0-9]+$") {
		strip(2);
		$rU = "+" + $rU;
		return;
	}
	if ($rU =~ "^[1-9][0-9]+$")
		$rU = "+" + $rU;
}

# ---------------------------------------------------------------------------
#  Stateful relay
# ---------------------------------------------------------------------------
route[RELAY] {
	if (!t_relay())
		send_reply(500, "Internal Server Error");
	exit;
}
